config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile'},
             controllers: {
                 omniauth_callbacks: 'omniauth_callbacks',
                 registrations: 'registrations'
             }

  resources :users, only: :show
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  get '/preload' => 'reservations#preload'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  geocoded_by :address
  # If address is updated, geocode will generate a new set of latitude and longitude
  after_validation :geocode, if: :address_changed?

  validates :home_type, :room_type, :accomodate, :bedroom, :bathroom, :listing_name, :summary, :address, presence: true
  validates :listing_name, length: {maximum: 50}
  validates :summary, length: {maximum: 500}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  validates :fullname, length: {maximum: 50}, presence: true

  has_many :rooms
  has_many :reservations

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.fullname = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0, 20]
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :fullname
    devise_parameter_sanitizer.for(:account_update) << :fullname << :phone_number << :description
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:noteice, :success, kind: 'Google') if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: room.id)

    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :authenticate_user!

	def preload
		room = Room.find(params[:room_id])
		today = Date.today
		reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

		render json: reservations	
	end

	def create
		@reservation = current_user.reservations.create(reservation_params)

		redirect_to @reservation.room, notice: "Your reservation has been created..."
	end

	private
		def reservation_params
			params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)
		end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update]
  # User must be authneticated before every controller action, except for show
  before_action :authenticate_user!, except: [:show]

  def new
    @room = current_user.rooms.build
  end

  def show
    @photos = @room.photos
  end

  def index
    @rooms = current_user.rooms
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end

      @photos = @room.photos
      redirect_to edit_room_path (@room), notice: "Saved..."
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      redirect_to edit_room_path(@room), notice: "Updated..."
    else
      render :edit
    end
  end

  def edit
    if current_user.id == @room.user.id
     @photos = @room.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(
        :home_type, :room_type, :accomodate,
        :bedroom, :bathroom, :listing_name,
        :summary, :address, :is_tv, :is_kitchen,
        :is_air, :is_heating, :is_internet, :price, :active
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    if user.image
      user.image
    else
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
	  <title>Airbnb</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
      <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    </head>

	<body>
		<%= render 'shared/navbar' %>
		<%= render 'shared/message' %>
		<div class="container main-container">
			<%= yield %>
		</div>

	</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_list.html.erb
<% if @photos %>
    <div class="row">
      <% @photos.each do |photo|  %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag photo.image.url() %>
            </div>
            <div class="panel-body">
              <span class="pull-right">
                <%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                    <i class="fa fa-times fa-lg"></i>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>
	
	<div class="row">
		<div class="col-md-6">
			<label>Check In</label>
			<%= f.text_field :start_date, placeholder: 'Start Date', class: 'form-control', readonly: 'true' %>
		</div>
		<div class="col-md-6">
			<label>Check Out</label>
			<%= f.text_field :end_date, placeholder: 'End Date', class: 'form-control', disabled: 'true', readonly: 'true'  %>
		</div>
	</div>

	<%= f.hidden_field :room_id, value: @room.id %>
	<%= f.hidden_field :price, value: @room.price %>
	<%= f.hidden_field :total, value: 'reservation_total' %>
	
	<div id="preview" style = "display:none;">
		<h4><span id="message"></span></h4>	
		<table class = "reservation-table">
			<tbody>
				<tr>
					<td>Day(s)</td>
					<td><span id="reservation_days"></span></td>
				</tr>
				<tr>
					<td>Total</td>
					<td><span id="reservation_sum"></span></td>
				</tr>
			</tbody>
		</table>
	</div>

	<br/>
	<%= f.submit "Book Now", class: "btn btn-primary" %>
<% end %>

<script>

	function unavailable(date) {
		dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		return [$.inArray(dmy, unavailableDates) == -1];
	}

	$(function() {

		unavailableDates = [];

		$.ajax({
			url: '/preload',
			data: {'room_id': <%= @room.id %>},
			dataType: 'json',
			success: function(data) {

				$.each(data, function(arrID, arrValue) {
					for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
						console.log(d);
						unavailableDates.push($.datepicker.formatDate('dd-mm-yy', d));
					};
				});
				console.log(unavailableDates);
				$('#reservation_start_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#reservation_end_date').datepicker("option", "minDate", selected);
						$('#reservation_end_date').attr('disabled', false);
					}
				});

				$('#reservation_end_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#reservation_start_date').datepicker("option", "maxDate", selected);
					}
				});
			}
		});

		

	});
</script>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">
      <%= form_for @room, html: {multipart: true} do |f| %>
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <!--[key, value]-->
              <%= f.select :home_type, [["Appartment", "Appartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], id: 'home_type', prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]], prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accomodate</label>
              <%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6+", 6]], prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>

        </div>

        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bedrooms</label>
              <%= f.select :bedroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Bathrooms</label>
              <%= f.select :bathroom, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: 'Select...', class: 'form-control' %>
            </div>
          </div>
        </div>

        <div class="row">
            <div class="form-group">
              <label>Listing Name</label>
              <%= f.text_field :listing_name, placeholder: 'Be clear and descriptive', class: 'form-control' %>
            </div>
        </div>

          <div class="row">
            <div class="form-group">
              <label>Summary</label>
              <%= f.text_area :summary, rows: 5, placeholder: 'Tell about your accomodation!', class: 'form-control' %>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <label>Address</label>
              <%= f.text_field :address, placeholder: 'What is your address?', class: 'form-control' %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label><%= f.check_box :is_tv %> TV</label>
              </div>
              <div class="form-group">
                <label><%= f.check_box :is_kitchen %> Kitchen</label>
              </div>
              <div class="form-group">
                <label><%= f.check_box :is_internet %> Internet</label>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label><%= f.check_box :is_heating %> Heating</label>
              </div>
              <div class="form-group">
                <label><%= f.check_box :is_air %> Air Conditioning</label>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label>Nightly Price</label>
                <div class="input-group">
                  <div class="input-group-addon">$</div>
                  <%= f.text_field :price, placeholder: 'e.g. $100', class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <span class="btn btn-default btn-file">
                  <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
                  <%= file_field_tag "images[]", type: :file, multiple: true %>
                </span>
              </div>
            </div>
          </div>

          <div id="photos">
            <%= render 'photos/list' %>
          </div>

          <div class="row">
            <div class="form-group">
              <label><%= f.check_box :active %> Active</label>
            </div>
          </div>

          <div class="actions">
            <%= f.submit "Save", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listing", rooms_path, class:"sidebar-link active"%></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", rooms_path, class:"sidebar-link"%></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Listings
			</div>
			<div class="panel-body">
				<% @rooms.each do |room| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %>
						</div>
						<div class="col-md-7">
							<h4><%= room.listing_name %></h4>
						</div>
						<div class="col-md-3 right">
							<%= link_to "Update", edit_room_path(room), class: "btn btn-primary"%>
						</div>
					</div>
					<hr/>
				<% end %>
			</div>
		</div>
	</div>	
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		
		<!-- Image -->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<%= image_tag @photos[0].image.url, class: "img-responsive" if @photos.length > 0 %>
			</div>
		</div>

		<br/>
		<!-- Main Info -->
		<div class="row">
			<div class="col-md-8">
				<div class="row">
					<div class="col-md-3 text-center">
						<%= image_tag avatar_url(@room.user), class:"img-circle avatar-large" %>
						<br/><br/>
						<%= @room.user.fullname %>
					</div>
					<div class="col-md-9">
						<h4><%= @room.listing_name %></h4>
						<%= @room.address %>

						<div class="row text-centre row-space-1">
							<div class="col-sm-3">
								<i class="fa fa-home fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-user fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-bed fa-2x"></i>
							</div>
							<div class="col-sm-3">
								<i class="fa fa-ship fa-2x"></i>
							</div>
						</div>
						<div class="row text-centre row-space-1">
							<div class="col-sm-3">
								<%= @room.home_type %>
							</div>
							<div class="col-sm-3">
								<%= @room.accomodate %> <%= @room.accomodate > 1 ? "Guests":"Guest"  %>
							</div>
							<div class="col-sm-3">
								<%= @room.bedroom %> <%= @room.bedroom > 1 ? "Bedrooms":"Bedroom"  %>
							</div>
							<div class="col-sm-3">
								<%= @room.bathroom %> <%= @room.bedroom > 1 ? "Bathrooms":"Bathroom"  %>
							</div>
						</div>

					</div>
				</div>
			</div>
			<div class="col-md-4">
				<!-- Reservation form -->
				<%= render 'reservations/form' %>
			</div>
		</div>

		<!-- About -->
		<div class="row">
			<div class="col-md-12">
				<h2>About This Listing</h2>
				<p><%= @room.summary%></p>
			</div>
		</div>

		<!-- Amenities -->
		<div class="row">
			<div class="col-md-2">
				<h2>Amenities</h2>
			</div>
			<div class="row">
				<div class="col-md-10">
					<div class="row">
						<div class="col-md-6">
							<ul class="amenities">
								<li class="<%= 'text-line-through' unless @room.is_tv%>">TV</li>
								<li class="<%= 'text-line-through' unless @room.is_kitchen%>">Kitchen</li>
								<li class="<%= 'text-line-through' unless @room.is_internet%>">Internet</li>	
							</ul>
						</div>
						<div class="col-md-6">
							<ul class="amenities">
								<li class="<%= 'text-line-through' unless @room.is_heating %>">Heating</li>
								<li class="<%= 'text-line-through' unless @room.is_air %>">Air Conditioning</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Carousel -->
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div id="myCarousel" class="carousel slide" data-ride="carousel">
				  <!-- Indicators -->
				  <% if @photos %>
					  <ol class="carousel-indicators">
					  	<% @photos.each do |photo| %>
					    	<li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
					    <% end%>
					  </ol>
				  <% end %>
				  <!-- Wrapper for slides -->
				  <div class="carousel-inner" role="listbox">
				    <% if @photos %>
				    	<% @photos.each do |photo| %>
						    <div class="item <%= 'active' if photo.id.equal? @photos[0].id %>">
						      <%= image_tag photo.image.url()%>
						    </div>
					    <% end %>
				    <% end %>
				  </div>

				  <!-- Left and right controls -->
				  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
				    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
				    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>

			</div>
		</div>

		<br/>
		<hr>

		<!-- Google Map -->
		<div class="row">
			<div class="col-md-12">
				<div id="map">
					
				</div>
				<style>
					#map{
						width: 100%;
						height: 400px;
					}
				</style>
				<script src="https://maps.googleapis.com/maps/api/js"></script>
			    <script>
			      function initialize() {
			        var mapCanvas = document.getElementById('map');
			        var mapOptions = {
			          center: new google.maps.LatLng(<%= @room.latitude %>, <%= @room.longitude %>),
			          zoom: 14,
			          mapTypeId: google.maps.MapTypeId.ROADMAP
			        }
			        var map = new google.maps.Map(mapCanvas, mapOptions);

			        var marker = new google.maps.Marker({
			        	position: new google.maps.LatLng(<%= @room.latitude %>, <%= @room.longitude %>),
			        	title: "Airbnb Clone"
			        });
			        marker.setMap(map);
			      }
			      google.maps.event.addDomListener(window, 'load', initialize);
			    </script>

			</div>
		</div>

		<!-- Close by Rooms -->
		<% if @room.nearbys.size > 0 %>
			<h3>Nearby</h3>
			<div class="row">
				<!-- Find nearby rooms within 10 miles radius -->
				<% for room in @room.nearbys(10) %>
					<div class="col-md-3">
						<div class="panel panel-default">
							<div class="panel-heading preview">
								<%= image_tag room.photos[0].image.url(:medium) %>
							</div>
							<div class="panel-body">
								<%= link_to room.listing_name, room %>
								(<%= room.distance.round(2) %> miles away)
							</div>
						</div>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "airbnb", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">Your Trips</a></li>
              <li><a href="#">Wish Lists</a></li>
              <li><%= link_to "Edit Profile",  edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Account Setting</a></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
        <li>
          <a href="#"><i class="fa fa-envelope-o"></i> Messages</a>
        </li>
        <li>
          <a href="#"><i class="fa fa-home fa-lg"></i> Become a Host</a>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_social_media_authentication.html.erb
<% facebook_logo = "fb-logo.png"  %>
<% google_logo = "google-logo.png" %>
<div class="row">
  <%= link_to image_tag(facebook_logo, size: '20') + " Login with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-primary facebook-btn" %>
</div>
<div class="row google-row">
  <%= link_to image_tag(google_logo, size: '25') + " Login with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-primary google-btn" %>
</div>

app/views/users/show.html.erb
<div class="row"> 
	<div class="col-md-3">
		<div class="center">
			<%= image_tag avatar_url(@user), class: "avatar-full"%>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">Verification</div>
			<div class="panel-body">
				Email</br>
				Phone number
			</div>
		</div>
	</div>

	<div class="col-md-9">
		<h2><%= @user.fullname %></h2>
		<div class="description row-space-3">
			<%= @user.description %>
		</div>
	</div>
</div>